### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by hackebrot** [hackebrot/pytest-tricks#16]
cc @ionelmc :grin:

**Comment by ionelmc** [comment]
Eh well, it's hard to motivate here since Pelican has RSS support and I use it a lot :-)

**Comment by ionelmc** [comment]
This looks like the right thing https://github.com/ajdavis/lektor-atom

**Comment by ionelmc** [comment]
Looks like it wants newer Lektor: https://github.com/ajdavis/lektor-atom/issues/2

**Comment by hackebrot** [comment]
Done 67335d0b00f39cd382e42182ff702b84bf78f38b 😸 

http://hackebrot.github.io/pytest-tricks/atom.xml
