### ISSUE TITLE
Idea: explain indirect parametrization

### ISSUE THREAD

**Issue by ionelmc** [hackebrot/pytest-tricks#25]
Just found *today* that this feature exists: http://pytest.org/latest/example/parametrize.html?highlight=indirect#apply-indirect-on-particular-arguments

I think it's not so well known.

**Comment by hackebrot** [comment]
Thank you @ionelmc! 🙇 

I agree it is a powerful feature that is underused.

Do you want to write a post for that? If not, I'll write something during the sprints or on return flight 😁
